import {StyleSheet} from 'react-native';
import {COLOR, commonStyles, width} from '../../../../themes/StyleGuides';

const styles = StyleSheet.create({
  container: {},
  AmmountContainer: {
    width: '90%',
    backgroundColor: COLOR.gray_7,
    alignSelf: 'center',
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: '5%',
  },
  titleContainer: {
    height: 40,
    marginBottom: '6%',
    backgroundColor: COLOR.perpal,
    justifyContent: 'center',
    borderRadius: 14,
  },
  title: {
    fontSize: 16,
    fontWeight: '700',
    color: COLOR.whites,
    marginLeft: '3.6%',
  },
  Expire: {marginBottom: '7%'},
  itemListContainer: {...commonStyles.verticleView, marginLeft: '4%'},
  titleListText: {
    fontSize: 12,
    color: COLOR.gray_5,
    marginLeft: '6%',
    marginBottom: '1.5%',
    marginTop: '1.5%',
    fontWeight: '700',
  },
  dropDown: {
    width: 12,
    height: 12,
    resizeMode: 'contain',
  },
  itemcontainer: {
    width: width * 0.43,
    height: 33,
    paddingHorizontal: '7%',
    backgroundColor: COLOR.whites,
    borderRadius: 12,
    marginBottom: '0.7%',
    ...commonStyles.verticleView,
  },
  DropDownBtn: {
    ...commonStyles.verticleView,
    height: 25,
    backgroundColor: COLOR.perpal,
    borderRadius: 7,
    alignSelf: 'flex-end',
    paddingHorizontal: '3%',
    alignItems: 'center',
    marginTop: '5%',
    marginRight: '3.7%',
  },
  DropIcon: {width: 11, height: 11, resizeMode: 'contain', marginTop: '1.8%'},
  DropDowntext: {fontSize: 11, fontWeight: '700', color: COLOR.whites},
  btnContainer: {
    ...commonStyles.horizontalView,
    justifyContent: 'flex-end',
  },
  paymentList: {
    backgroundColor: COLOR.gray_5,
    paddingVertical: '2%',
    borderRadius: 10,
    marginTop: '10%',
  },
  priceText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLOR.whites,
    alignSelf: 'flex-end',
    marginRight: '5%',
  },
  togalContainer: {
    height: 40,
    // marginBottom:"40%",
    backgroundColor: COLOR.perpal,
    borderRadius: 14,
    width: '100%',
    alignSelf: 'center',
    ...commonStyles.verticleView,
    paddingHorizontal: '5%',
  },
  titletogal: {
    fontSize: 16,
    fontWeight: '700',
    color: COLOR.whites,
  },

  titleStyle: {
    fontSize: 12,
    color: COLOR.gray_5,
    marginLeft: '6%',
    marginBottom: '1.5%',
    marginTop: '1.5%',
    fontWeight: '700',
  },
  DiscountTitle: {
    fontSize: 12,
    fontWeight: '600',
    color: COLOR.gray_6,
    marginLeft: '4%',
    marginTop: '2%',
  },

  Discription: {
    fontSize: 9,
    fontWeight: '400',
    color: COLOR.gray_5,
    width: '90%',
    alignSelf: 'center',
    marginTop: '1%',
  },
  checkBtn: {
    ...commonStyles.horizontalView,
    marginLeft: '5.5%',
    marginTop: '7%',
  },
  checkText: {
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.gray_5,
    marginLeft: '4%',
    
  },
  check: {width: 15, height: 15, resizeMode: 'contain'},
  Discount: {
    width: '20%',
    height: 35,
    padding: 0,
    borderRadius: 10,
    backgroundColor: COLOR.white1,
    color: COLOR.perpal_3,
    paddingHorizontal: '3%',
  },
  selectBtn: {
    width: 100,
    height: 35,
    borderRadius: 12,
    ...commonStyles.verticleView,
    borderWidth: 1,
    borderColor: COLOR.perpal,
    overflow: 'hidden',
  },
  ItemDropDown: {
    width: width * 0.43,
    backgroundColor: COLOR.whites,
    height: 90,
    position: 'absolute',
    top: width * 0.16,
    zIndex: 10,
    borderRadius: 10,

    padding: '2%',
  },
  itmeDropDownText: {
    fontSize: 10,
    fontWeight: '400',
    color: COLOR.gray_15,
  },
  ApplyEarlyText: {
    width: '40%',
    height: 35,
    padding: 0,
    borderRadius: 10,
    backgroundColor: COLOR.white1,
    fontSize: 7,
    paddingHorizontal: '3%',
    color: COLOR.perpal_3,
  },
  DiscountModal: {
    width: '90%',
    height: 70,
    backgroundColor: COLOR.whites,
    borderRadius: 10,
    elevation: 10,
    position: 'absolute',
    bottom: '25%',
    alignSelf: 'center',
  },
});

export default styles;
