import {StyleSheet} from 'react-native';
import {COLOR, commonStyles, hp} from '../../../../themes/StyleGuides';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLOR.lightBlack,
    ...commonStyles.center,
  },
  modal: {
    // paddingHorizontal: '4%',
    borderRadius: 10,
    backgroundColor: COLOR.white1,
    width: '90%',
  },
  titleContainer: {
    ...commonStyles.verticleView,
    marginTop: '3%',
    paddingHorizontal: '5%',
  },
  title: {fontSize: 20, fontWeight: '700', color: COLOR.gray_5},

  btnContainer: {
    ...commonStyles.horizontalView,
    alignSelf: 'flex-end',
    marginTop: '10%',
    marginBottom: '10%',
  },
  btnSave: {
    paddingHorizontal: '5%',
    paddingVertical: '2%',
    borderRadius: 8,
    marginRight: '5%',
    ...commonStyles.center,
  },
  SaveBtnText: {fontSize: 12, fontWeight: '700', color: COLOR.whites},
  Circle: {
    width: 35,
    height: 35,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: COLOR.perpal_3,
    ...commonStyles.center,
  },
  line: {width: 80, height: 1, backgroundColor: COLOR.gray_7},
  textUpload: {fontSize: 12, fontWeight: '700', color: COLOR.perpal_3},
  number: {fontSize: 13, fontWeight: '700', color: COLOR.perpal_3},
  UploadIcon: {
    width: 30,
    height: 30,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: '8%',
    marginBottom: '3%',
  },
  UploadText: {
    fontSize: 14,
    fontWeight: '700',
    color: COLOR.perpal_3,
    alignSelf: 'center',
  },
  disText: {
    fontSize: 10,
    fontWeight: '800',
    color: COLOR.gray_5,
    textAlign: 'center',
  },
  DownloadText: {
    fontSize: 10,
    fontWeight: '400',
    color: COLOR.gray_5,
    textAlign: 'center',
  },
  RemoveText: {fontSize: 12, fontWeight: '400', color: COLOR.perpal_3},
  selectedDoc: {
    width: '90%',
    backgroundColor: COLOR.whites,
    height: 120,
    alignSelf: 'center',
    marginTop: '5%',
    borderRadius: 14,
    overflow: 'hidden',
  },
  tickcheck: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
    alignSelf: 'center',
    marginTop: '10%',
  },
  tick: {width: 15, height: 15, resizeMode: 'contain', tintColor: COLOR.whites},
  matchViewText: {
    fontSize: 11,
    color: COLOR.gray_5,
    fontWeight: '800',
    alignSelf: 'center',
    marginTop: '5%',
    marginBottom: '3%',
  },
  MatchLinkField: {
    width: '90%',
    height: 35,
    borderRadius: 10,
    backgroundColor: COLOR.gray_7,
    ...commonStyles.horizontalView,
    paddingHorizontal: '5%',
    alignSelf: 'center',
  },
  Error: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    tintColor: COLOR.primary,
  },
  Table: {
    overflow: 'hidden',
    width: '100%',
    backgroundColor: COLOR.gray_7,
    borderRadius: 10,
  },
  tabHeaderContainer: {
    width: 80,
    paddingVertical: '3%',
    backgroundColor: COLOR.perpal_3,
    ...commonStyles.center,
    height: hp(9),
    marginBottom: 1,
  },
  tabHeadreText: {
    fontSize: 10,
    fontWeight: '500',
    color: COLOR.whites,
    textAlign: 'center',
  },
  tabHeaderContainers: {
    width: 80,
    paddingVertical: '3%',
    backgroundColor: COLOR.perpal_3,
    ...commonStyles.center,
    marginBottom: 1,
    height: 70,
  },
  Downloadtext: {fontSize: 12, fontWeight: '700', color: COLOR.gray_5},
  DownloadBtn: {
    ...commonStyles.verticleView,
    width: '50%',
    height: 35,
    borderRadius: 10,
    alignSelf: 'center',
    backgroundColor: COLOR.whites,
    paddingHorizontal: '5%',
    marginTop: '5%',
  },
  DownloadIcon: {width: 15, height: 15, resizeMode: 'contain'},
  circleView: {
    width: 14,
    height: 14,
    borderRadius: 10,
    backgroundColor: COLOR.primary,
  },
});
export default styles;
