import {StyleSheet} from 'react-native';
import {COLOR, FONT, commonStyles, hp, wp} from '../../../themes/StyleGuides';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLOR.white1,
  },
  ListContainer: {
    paddingBottom: '4%',
    marginTop: '1%',
  },
  titleStyle: {
    fontSize: 13,
    fontFamily: FONT.Geist_SemiBold,
    color: COLOR.darkGray,
    alignSelf: 'center',
    marginVertical: '2%',
  },
  BottomContainer: {
    ...commonStyles.verticleView,
    height: 35,
    width: '95%',
    paddingHorizontal: '3%',
    borderWidth: 1,
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: COLOR.whites,
  },
  InputStyle: {
    fontSize: 13,
    color: COLOR.black,
    justifyContent: 'center',
    flex: 1,
    padding: 0,
  },

  TextInputConteiner: {
    backgroundColor: COLOR.whites,
    borderColor: COLOR.gray,
    ...commonStyles.verticleView,
    paddingHorizontal: '3%',
  },
  IconStyle: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    tintColor: COLOR.DarkBlue,
  },
  SendButton: {paddingHorizontal: '1%'},
  SendIcon: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    tintColor: COLOR.primary,
  },
  dayContainer: {...commonStyles.verticleView, paddingHorizontal: '6%'},
  dateLineBar: {width: '40%', height: 2, backgroundColor: COLOR.gray},
  dayStyle: {
    fontSize: 12,
    fontFamily: FONT.Geist_Medium,
    color: COLOR.black,
  },
  btnContainer: {
    ...commonStyles.verticleView,
    marginLeft: '3%',
    marginTop: hp('3%'),
    width: '42%',
    marginBottom: '2%',
  },
  btnLast: {
    paddingHorizontal: '6%',
    paddingVertical: '1.3%',
    backgroundColor: COLOR.perpal,
    borderRadius: 5,
  },

  TextinputsCOntainer: {
    alignSelf: 'center',
    backgroundColor: COLOR.white1,
  },
  SmSText: {fontSize: 12, fontWeight: '700', color: COLOR.gray_15},
  containertitle: {
    ...commonStyles.verticleView,
    marginVertical: '2%',
    paddingHorizontal: '3%',
  },
  TitleCOntainer: {
    ...commonStyles.verticleView,
    width: '65%',
    alignSelf: 'flex-end',
    marginRight: '5%',
  },
  Unassignedbtn: {
    height: 15,
    backgroundColor: COLOR.white1,
    borderRadius: 2,
    ...commonStyles.verticleView,
    paddingHorizontal: 3,
    marginRight: '5%',
  },
  modalText: {fontSize: 6, fontWeight: '700', color: COLOR.whites},
  statusbtn: {
    paddingVertical: '0.5%',
    borderRadius: 5,
    paddingHorizontal: 5,
    marginRight: 4,
  },
  DropDownIcon: {
    width: 8,
    height: 8,
    resizeMode: 'center',
    tintColor: COLOR.gray_5,
  },
  modals: {
    position: 'absolute',
    alignSelf: 'flex-end',
    width: wp('35%'),
    backgroundColor: COLOR.whites,
    zIndex: 1000,
    right: 20,
    borderRadius: 15,
    paddingVertical: hp('2%'),
    borderWidth: 1,
    borderColor: COLOR.black,
    top: hp('11.5%'),
  },
  modalItem: {
    paddingHorizontal: '8%',
    paddingVertical: '2%',
    borderRadius: 5,
    alignSelf: 'flex-start',
    marginVertical: '2%',
    marginLeft: '10%',
  },
  ThreeIcon: {width: 10, height: 15, resizeMode: 'contain'},
  sattingText: {
    fontSize: 11,
    fontWeight: '400',
    color: COLOR.gray_5,
    marginTop: '2%',
  },
  Sattingmodals: {
    position: 'absolute',
    alignSelf: 'flex-end',
    backgroundColor: COLOR.whites,
    zIndex: 1000,
    right: 20,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: COLOR.black,
    top: hp('11%'),
    paddingHorizontal: hp('2%'),
    justifyContent: 'center',
  },
  lastbtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLOR.whites,
  },

  SMSEmailContainer: {
    position: 'absolute',
    alignSelf: 'center',
    bottom: 0,
    backgroundColor: COLOR.white1,
  },
});
