import {StyleSheet} from 'react-native';
import { COLOR, commonStyles, hp } from '../../../themes/StyleGuides';

const styles = StyleSheet.create({
  container: {
    marginTop: '5%',
    marginBottom: '20%',
  },
  AmmountContainer: {
    width: '94%',
    backgroundColor: COLOR.gray_7,
    alignSelf: 'center',
    borderRadius: 14,
    overflow: 'hidden',
    marginBottom: '5%',
  },
  titleContainer: {
    height: 40,
    marginBottom: '2%',
    backgroundColor: COLOR.perpal,
    justifyContent: 'center',
    borderRadius: 14,
  },

  title: {
    fontSize: 16,
    fontWeight: '700',
    color: COLOR.whites,
    marginLeft: '3.6%',
  },
  ReviewContainer: {
    width: '93%',
    backgroundColor: COLOR.whites,
    borderRadius: 10,
    paddingVertical: '3%',
    alignSelf: 'center',
    marginBottom: '5%',
    marginTop: '6%',
  },
  ReviewView: {
    ...commonStyles.verticleView,
    width: '90%',
    alignSelf: 'center',
    marginTop: '2%',
    marginBottom: '2%',
  },
  ReviewText: {fontSize: 9, fontWeight: '700', color: COLOR.gray_5},
  rating: {fontSize: 9, fontWeight: '500', color: COLOR.gray_5},
  listContainer: {
    width: '94%',
    borderRadius: 15,
    backgroundColor: COLOR.gray_7,
    ...commonStyles.verticleView,
    alignSelf: 'center',
    marginTop: '2%',
    paddingHorizontal: '3%',
    paddingVertical: '3%',
  },
  listIcon: {width: 30, height: 30, resizeMode: 'contain'},
  listTitle: {fontSize: 9, fontWeight: '700', color: COLOR.gray_5},
  listDoscription: {fontSize: 7, fontWeight: '400', color: COLOR.gray_5},
  widgetText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLOR.gray_5,
    alignSelf: 'center',
  },
  DisplayText: {
    fontSize: 10,
    fontWeight: '400',
    color: COLOR.gray_5,
    alignSelf: 'center',
    marginTop: '1%',
  },
  CustomContainer: {
    backgroundColor: COLOR.gray_7,
    width: '49%',
    height: 100,
    // paddingVertical:"5%",
    borderRadius: 10,
    overflow: 'hidden',
  },
  ListingBtn: {
    backgroundColor: COLOR.perpal_3,
    borderRadius: 8,
    alignSelf: 'center',
    marginTop: '3%',
    marginBottom: '5%',
    ...commonStyles.center,
    height: 25,
    paddingHorizontal: '5%',
  },
  ListBtnText: {fontSize: 12, fontWeight: '700', color: COLOR.whites},
  BoxRiviewText: {
    fontSize: 6,
    width: '70%',
    fontWeight: '400',
    color: COLOR.gray_5,
    alignSelf:"center",
    marginVertical:hp("2%")
  },
  ReviewBoxIcons: {
    width: 22,
    height: 22,
    borderRadius: 12,
    backgroundColor: COLOR.white1,
    ...commonStyles.center,
    position: 'absolute',
    alignSelf: 'center',
    top: -12,
  },
  BoxTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: COLOR.gray_5,
    marginBottom: '2%',
  },
  comment: {
    width: '90%',
    height: 120,
    borderRadius: 15,
    backgroundColor: COLOR.whites,
    textAlignVertical: 'top',
    alignSelf: 'center',
    marginTop: '4%',
    color: COLOR.gray_5,
    padding: 10,
  },
});

export default styles;
